import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Head from "next/head";
import useKeypress from "react-use-keypress";
import { About } from "../components/About";
import { Hero } from "../components/Hero";
export default function Home({open,setOpen}) {
  useKeypress(["Enter"], (event) => {
    if (event.key === "Enter") {
      setOpen(false);
    }
  });
  return (
    <>
      <Head>
        <title>FW</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container maxWidth="md" sx={{ marginTop: 2, marginBottom: "auto" }}>
        <Hero></Hero>
      </Container>
      <Box
        id="about"
        sx={{
          background: "rgba(29, 31, 42, 0.5)",
        }}
      >
        <Container maxWidth="md" sx={{ marginTop: 2, marginBottom: "auto" }}>
          <About open={open}></About>
        </Container>

      <Box
        id="projects"
        sx={{
          padding:"1%",
          marginTop: "2%",
          
        }}
      >
      </Box>
      </Box>
    </>
  );
}
