import Container from "@mui/material/Container";
import Head from "next/head";
import { useState } from "react";
import { Hero } from "../components/Hero";
import { Projects } from "../components/Projects";
import { Skills } from "../components/Skills";
export default function Home() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md" sx={{ marginTop: 2, marginBottom: "auto" }}>
        <Hero></Hero>
        <Skills open={open} setOpen={setOpen}></Skills>
        <Projects open={open} setOpen={setOpen}></Projects>
      </Container>
    </>
  );
}
